### ISSUE TITLE
Setup and share a public recurring calendar invite for Community Currencies NOW calls

### ISSUE THREAD

**Issue by Kisgus** [CommunityCurrency/Governance#1]

**Comment by JuliointheStudio** [comment]
done https://currency.community/d/8-community-currencies-now-calendar-link

**Comment by Kisgus** [comment]
Reopened this issue as it's still not working, I've tested it on some people and they all get "requested event not found"
